#!/usr/bin/env bash
# Generate the NSS (cert9.db) fixtures used by the truststore tests.
#
#   bash tools/testing/gen_nss_fixtures.sh
#
# Needs `certutil` (nss-tools / libnss3-tools / `brew install nss`) and a built
# certdiag. Generation-time only: the tests read the committed databases and
# need nothing installed.
#
# These live under internal/certlib/truststore/testdata, not under
# tools/testing/edgecases/fixtures: that tree is gitignored and fully
# regenerated by the harness whenever its manifest goes stale, which would
# delete anything certutil put there.
#
# Note from M29 implementation: re-adding the same certificate under a different
# nickname OVERWRITES its trust rather than creating a second entry, so every
# fixture below uses a distinct certificate.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="$REPO_ROOT/certdiag_app/internal/certlib/truststore/testdata/nss"
CERTDIAG="$REPO_ROOT/certdiag_app/dist/certdiag"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

command -v certutil >/dev/null || { echo "certutil not found" >&2; exit 1; }
[ -x "$CERTDIAG" ] || { echo "build certdiag first: (cd certdiag_app && task build)" >&2; exit 1; }

rm -rf "$OUT"
mkdir -p "$OUT"

mkcert() { # $1=name  $2=CN
  "$CERTDIAG" create-cert --with-key --ca \
    --subject "CN=$2,O=certdiag NSS fixture" \
    --days 7300 -a ecdsa --curve p256 \
    -o "$WORK/$1.pem" >/dev/null
}

mkprofile() { # $1=dir  $2=cert name  $3=trust flags
  local dir="$OUT/$1"
  mkdir -p "$dir"
  certutil -N -d "sql:$dir" --empty-password >/dev/null 2>&1
  if [ -n "${2:-}" ]; then
    certutil -A -n "$2" -t "$3" -i "$WORK/$2.pem" -d "sql:$dir" >/dev/null 2>&1
  fi
  # certutil leaves key4.db and pkcs11.txt; only cert9.db is needed and only it
  # should be committed.
  find "$dir" -type f ! -name 'cert9.db' -delete
  echo "  $1: $(ls "$dir")"
}

for n in trusted distrusted serverauth notrust; do
  mkcert "$n" "NSS Fixture ${n}"
done

mkprofile profile-trusted     trusted     "CT,C,C"
mkprofile profile-distrusted  distrusted  "p,p,p"
mkprofile profile-serverauth  serverauth  "C,,"
mkprofile profile-notrust     notrust     ",,"
mkprofile profile-empty       ""          ""

# A Firefox-style profile root: two profiles, one default, one relative path and
# one absolute-style entry that does not exist (must be skipped, not fail).
mkdir -p "$OUT/firefox-root/Profiles/aaaa1111.default-release"
cp "$OUT/profile-trusted/cert9.db" "$OUT/firefox-root/Profiles/aaaa1111.default-release/"
mkdir -p "$OUT/firefox-root/Profiles/bbbb2222.other"
cp "$OUT/profile-serverauth/cert9.db" "$OUT/firefox-root/Profiles/bbbb2222.other/"

cat > "$OUT/firefox-root/profiles.ini" <<'INI'
[Profile2]
Name=ghost
IsRelative=1
Path=Profiles/cccc3333.missing

[Profile1]
Name=other
IsRelative=1
Path=Profiles/bbbb2222.other

[Profile0]
Name=default-release
IsRelative=1
Path=Profiles/aaaa1111.default-release
Default=1

[General]
StartWithLastProfile=1
Version=2
INI

echo "  firefox-root: profiles.ini with 3 entries, 2 present, 1 default"
echo "fixtures written to $OUT"
