package tls

import (
	"encoding/hex"
	"strings"
	"testing"
)

const sampleKeyLog = `# SSL/TLS secrets log file, generated by NSS
CLIENT_RANDOM aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899 0011223344556677
SERVER_HANDSHAKE_TRAFFIC_SECRET AABBCCDDEEFF00112233445566778899AABBCCDDEEFF00112233445566778899 8899aabbccddeeff
CLIENT_HANDSHAKE_TRAFFIC_SECRET aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899 ffeeddccbbaa9988

# a blank line and a comment above; a malformed line below
GARBAGE_LINE_WITH_TWO_FIELDS only-two
BAD_HEX aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899 zzzz
`

func mustDecode(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func TestParseKeyLog(t *testing.T) {
	kl, err := ParseKeyLog(strings.NewReader(sampleKeyLog))
	if err != nil {
		t.Fatal(err)
	}
	if kl.Len() != 1 {
		t.Fatalf("expected 1 client random, got %d", kl.Len())
	}

	cr := mustDecode(t, "aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899")

	tests := []struct {
		label   string
		wantHex string
	}{
		{KeyLogClientRandom, "0011223344556677"},
		{KeyLogServerHandshakeTrafficSecret, "8899aabbccddeeff"}, // uppercase random in file, must still match
		{KeyLogClientHandshakeTrafficSecret, "ffeeddccbbaa9988"},
	}
	for _, tt := range tests {
		t.Run(tt.label, func(t *testing.T) {
			secret, ok := kl.Secret(cr, tt.label)
			if !ok {
				t.Fatalf("label %s not found", tt.label)
			}
			if hex.EncodeToString(secret) != tt.wantHex {
				t.Errorf("got %x, want %s", secret, tt.wantHex)
			}
		})
	}
}

func TestKeyLogLookupMisses(t *testing.T) {
	kl, err := ParseKeyLog(strings.NewReader(sampleKeyLog))
	if err != nil {
		t.Fatal(err)
	}
	cr := mustDecode(t, "aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899")

	if _, ok := kl.Secret(cr, KeyLogServerTrafficSecret0); ok {
		t.Error("unexpected hit for absent label")
	}
	other := mustDecode(t, "1111111111111111111111111111111111111111111111111111111111111111")
	if _, ok := kl.Secret(other, KeyLogClientRandom); ok {
		t.Error("unexpected hit for absent client random")
	}
	// malformed lines must not have produced entries
	if _, ok := kl.Secret(cr, "GARBAGE_LINE_WITH_TWO_FIELDS"); ok {
		t.Error("malformed 2-field line was stored")
	}
	if _, ok := kl.Secret(cr, "BAD_HEX"); ok {
		t.Error("bad-hex secret line was stored")
	}
}

func TestParseKeyLogEmpty(t *testing.T) {
	kl, err := ParseKeyLog(strings.NewReader("# only a comment\n\n"))
	if err != nil {
		t.Fatal(err)
	}
	if kl.Len() != 0 {
		t.Fatalf("expected empty keylog, got %d", kl.Len())
	}
	if _, ok := kl.Secret([]byte{1, 2, 3}, KeyLogClientRandom); ok {
		t.Error("empty keylog returned a secret")
	}
}

func TestNilKeyLog(t *testing.T) {
	var kl *KeyLog
	if kl.Len() != 0 {
		t.Error("nil keylog Len != 0")
	}
	if _, ok := kl.Secret([]byte{1}, KeyLogClientRandom); ok {
		t.Error("nil keylog returned a secret")
	}
}
