package tls

import (
	"os"
	"strings"
	"testing"
)

// TestTables_Generated guards M31 M22: the name tables come from the IANA
// registries and carry their provenance; the codes that were "Unknown" in the
// audit resolve.
func TestTables_Generated(t *testing.T) {
	src, err := os.ReadFile("tables_gen.go")
	if err != nil {
		t.Fatal(err)
	}
	head := string(src[:min(600, len(src))])
	for _, want := range []string{"Code generated by tools/mktables", "DO NOT EDIT", "iana.org", "task refresh-tables"} {
		if !strings.Contains(head, want) {
			t.Errorf("tables_gen.go header lacks %q", want)
		}
	}
	cases := map[string]string{
		CipherSuiteName(0xccaa):        "TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
		CipherSuiteName(0x1301):        "TLS_AES_128_GCM_SHA256",
		NamedGroupName(0x11ec):         "X25519MLKEM768",
		NamedGroupName(29):             "x25519",
		SignatureAlgorithmName(0x0807): "ed25519",
		SignatureAlgorithmName(0x0804): "rsa_pss_rsae_sha256",
		CipherSuiteName(0xbeef):        "Unknown(0xbeef)",
	}
	for got, want := range cases {
		if got != want {
			t.Errorf("got %q, want %q", got, want)
		}
	}
	if len(cipherSuiteNames) < 300 || len(namedGroups) < 40 || len(signatureAlgorithms) < 30 {
		t.Errorf("tables look truncated: %d suites, %d groups, %d schemes", len(cipherSuiteNames), len(namedGroups), len(signatureAlgorithms))
	}
}

func TestWeakCipherSuite(t *testing.T) {
	weak := []string{
		"TLS_RSA_WITH_AES_128_GCM_SHA256", "TLS_NULL_WITH_NULL_NULL", "TLS_RSA_EXPORT_WITH_RC4_40_MD5",
		"TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA", "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA", "TLS_DH_anon_WITH_AES_128_CBC_SHA",
		"TLS_DHE_DSS_WITH_DES_CBC_SHA", "TLS_ECDHE_RSA_WITH_NULL_SHA", "TLS_KRB5_WITH_DES_CBC_SHA",
	}
	strong := []string{
		"TLS_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
		"TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA", "TLS_EMPTY_RENEGOTIATION_INFO_SCSV", "TLS_RSA_PSK_WITH_AES_128_GCM_SHA256",
	}
	for _, n := range weak {
		if !weakCipherSuite(n) {
			t.Errorf("%s should be weak", n)
		}
	}
	for _, n := range strong {
		if weakCipherSuite(n) {
			t.Errorf("%s should not be weak", n)
		}
	}
}
