// Command mktables regenerates certdiag's TLS name tables from the IANA
// registries and its Certificate Transparency log names from Google's log
// list. It needs the network and is run by hand (`task refresh-tables`); the
// generated files are committed so a build never needs it.
package main

import (
	"bytes"
	"encoding/base64"
	"encoding/csv"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

const (
	cipherURL = "https://www.iana.org/assignments/tls-parameters/tls-parameters-4.csv"
	groupURL  = "https://www.iana.org/assignments/tls-parameters/tls-parameters-8.csv"
	sigURL    = "https://www.iana.org/assignments/tls-parameters/tls-signaturescheme.csv"
	ctURL     = "https://www.gstatic.com/ct/log_list/v3/all_logs_list.json"
)

func main() {
	tlsOut := flag.String("tls-out", "pkg/packet_anal/tls/tables_gen.go", "output for the TLS tables")
	ctOut := flag.String("ct-out", "internal/certlib/extensions/ctlogs_gen.go", "output for the CT log names")
	flag.Parse()

	today := time.Now().UTC().Format("2006-01-02")
	ciphers, err := ianaTable(cipherURL, parseCipherValue)
	die(err)
	groups, err := ianaTable(groupURL, parseDecimalValue)
	die(err)
	sigs, err := ianaTable(sigURL, parseHexValue)
	die(err)
	logs, stamp, err := ctLogs()
	die(err)

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tools/mktables on %s; DO NOT EDIT.\n", today)
	fmt.Fprintf(&b, "//\n// Sources:\n//   %s\n//   %s\n//   %s\n", cipherURL, groupURL, sigURL)
	fmt.Fprintf(&b, "//\n// Regenerate with `task refresh-tables`.\n\npackage tls\n\n")
	writeTable(&b, "cipherSuiteNames", "IANA TLS Cipher Suites", ciphers, true)
	writeTable(&b, "namedGroups", "IANA TLS Supported Groups", groups, false)
	writeTable(&b, "signatureAlgorithms", "IANA TLS SignatureScheme", sigs, true)
	die(writeGo(*tlsOut, b.Bytes()))
	fmt.Printf("%s: %d cipher suites, %d groups, %d signature schemes\n", *tlsOut, len(ciphers), len(groups), len(sigs))

	b.Reset()
	fmt.Fprintf(&b, "// Code generated by tools/mktables on %s; DO NOT EDIT.\n", today)
	fmt.Fprintf(&b, "//\n// Source: %s (log_list_timestamp %s)\n", ctURL, stamp)
	fmt.Fprintf(&b, "//\n// Regenerate with `task refresh-tables`.\n\npackage extensions\n\n")
	fmt.Fprintf(&b, "// ctLogNames maps a CT log ID (hex SHA-256 of the log key) to its name.\nvar ctLogNames = map[string]string{\n")
	ids := make([]string, 0, len(logs))
	for id := range logs {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		fmt.Fprintf(&b, "\t%q: %q,\n", id, logs[id])
	}
	b.WriteString("}\n")
	die(writeGo(*ctOut, b.Bytes()))
	fmt.Printf("%s: %d logs\n", *ctOut, len(logs))
}

func die(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "mktables:", err)
		os.Exit(1)
	}
}

func fetch(url string) ([]byte, error) {
	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s: HTTP %s", url, resp.Status)
	}
	return io.ReadAll(resp.Body)
}

// ianaTable reads an IANA CSV whose first two columns are Value and
// Description, keeping single assigned values only.
func ianaTable(url string, parse func(string) (uint16, bool)) (map[uint16]string, error) {
	data, err := fetch(url)
	if err != nil {
		return nil, err
	}
	rows, err := csv.NewReader(bytes.NewReader(data)).ReadAll()
	if err != nil {
		return nil, fmt.Errorf("%s: %w", url, err)
	}
	out := map[uint16]string{}
	for i, row := range rows {
		if i == 0 || len(row) < 2 {
			continue
		}
		name := strings.TrimSpace(row[1])
		if name == "" || strings.HasPrefix(name, "Reserved") || strings.HasPrefix(name, "Unassigned") ||
			strings.HasPrefix(name, "Private Use") || strings.Contains(name, " ") {
			continue
		}
		code, ok := parse(strings.TrimSpace(row[0]))
		if !ok {
			continue
		}
		out[code] = name
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s: no assignments parsed", url)
	}
	return out, nil
}

// parseCipherValue reads "0xCC,0xAA".
func parseCipherValue(v string) (uint16, bool) {
	parts := strings.Split(v, ",")
	if len(parts) != 2 {
		return 0, false
	}
	hi, err1 := strconv.ParseUint(strings.TrimPrefix(parts[0], "0x"), 16, 8)
	lo, err2 := strconv.ParseUint(strings.TrimPrefix(parts[1], "0x"), 16, 8)
	if err1 != nil || err2 != nil {
		return 0, false
	}
	return uint16(hi)<<8 | uint16(lo), true
}

func parseDecimalValue(v string) (uint16, bool) {
	n, err := strconv.ParseUint(v, 10, 16)
	return uint16(n), err == nil
}

func parseHexValue(v string) (uint16, bool) {
	n, err := strconv.ParseUint(strings.TrimPrefix(v, "0x"), 16, 16)
	return uint16(n), err == nil
}

func writeTable(b *bytes.Buffer, name, source string, table map[uint16]string, hexKeys bool) {
	codes := make([]int, 0, len(table))
	for c := range table {
		codes = append(codes, int(c))
	}
	sort.Ints(codes)
	fmt.Fprintf(b, "// %s: %s.\nvar %s = map[uint16]string{\n", name, source, name)
	for _, c := range codes {
		if hexKeys {
			fmt.Fprintf(b, "\t0x%04x: %q,\n", c, table[uint16(c)])
		} else {
			fmt.Fprintf(b, "\t%d: %q,\n", c, table[uint16(c)])
		}
	}
	b.WriteString("}\n\n")
}

// ctLogs maps hex log IDs to a readable name from every operator's current
// and tiled logs, retired ones included, since old certificates cite them.
func ctLogs() (map[string]string, string, error) {
	data, err := fetch(ctURL)
	if err != nil {
		return nil, "", err
	}
	var list struct {
		Timestamp string `json:"log_list_timestamp"`
		Operators []struct {
			Name string `json:"name"`
			Logs []struct {
				Description string `json:"description"`
				LogID       string `json:"log_id"`
			} `json:"logs"`
			TiledLogs []struct {
				Description string `json:"description"`
				LogID       string `json:"log_id"`
			} `json:"tiled_logs"`
		} `json:"operators"`
	}
	if err := json.Unmarshal(data, &list); err != nil {
		return nil, "", fmt.Errorf("log list: %w", err)
	}
	out := map[string]string{}
	add := func(operator, desc, id string) error {
		raw, err := base64.StdEncoding.DecodeString(id)
		if err != nil || len(raw) != 32 {
			return fmt.Errorf("log %q: bad log_id %q", desc, id)
		}
		out[hex.EncodeToString(raw)] = cleanLogName(operator, desc)
		return nil
	}
	for _, op := range list.Operators {
		for _, l := range op.Logs {
			if err := add(op.Name, l.Description, l.LogID); err != nil {
				return nil, "", err
			}
		}
		for _, l := range op.TiledLogs {
			if err := add(op.Name, l.Description, l.LogID); err != nil {
				return nil, "", err
			}
		}
	}
	if len(out) < 20 {
		return nil, "", fmt.Errorf("log list: only %d logs parsed", len(out))
	}
	return out, list.Timestamp, nil
}

// cleanLogName turns "Google 'Argon2026h1' log" into "Google Argon2026h1"
// and makes sure the operator is named.
// quotedNickname matches the quoted log nickname in a description.
var quotedNickname = regexp.MustCompile(`'([^']+)'`)

func cleanLogName(operator, desc string) string {
	name := quotedNickname.ReplaceAllString(desc, "$1")
	name = strings.TrimSpace(strings.TrimSuffix(strings.TrimSuffix(name, " log"), " Log"))
	if !strings.HasPrefix(strings.ToLower(name), strings.ToLower(operator)) {
		name = operator + " " + name
	}
	return name
}

func writeGo(path string, src []byte) error {
	formatted, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("%s: %w\n%s", path, err, src)
	}
	return os.WriteFile(path, formatted, 0o644)
}
