package extensions

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"os"
	"strings"
	"testing"
)

// TestCTLogNames_Generated guards M31 M22: log names come from Google's log
// list with provenance, and a current log resolves by its ID.
func TestCTLogNames_Generated(t *testing.T) {
	src, err := os.ReadFile("ctlogs_gen.go")
	if err != nil {
		t.Fatal(err)
	}
	head := string(src[:min(400, len(src))])
	for _, want := range []string{"Code generated by tools/mktables", "DO NOT EDIT", "log_list_timestamp"} {
		if !strings.Contains(head, want) {
			t.Errorf("ctlogs_gen.go header lacks %q", want)
		}
	}
	if len(ctLogNames) < 50 {
		t.Errorf("only %d logs known", len(ctLogNames))
	}
	// Google Argon2026h1, log_id as published (SHA-256 of the log key).
	raw, _ := base64.StdEncoding.DecodeString("DleUvPOuqT4zGyyZB7P3kN+bwj1xMiXdIaklrGHFTiE=")
	if name := ctLogNames[hex.EncodeToString(raw)]; !strings.Contains(name, "Argon2026h1") {
		t.Errorf("Argon2026h1 resolves to %q", name)
	}
	for id, name := range ctLogNames {
		if len(id) != sha256.Size*2 || name == "" || strings.Contains(name, " '") || strings.Contains(name, "' ") {
			t.Errorf("malformed entry %q: %q", id, name)
		}
	}
}
